# 2019/09/18 Initial 

# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys

from logger import logger

class method_selenium():
    def __init__(self):
        self.driver = webdriver.Chrome()
        logger.info('{0}'.format("Initial Chrome Webbrowser!"))
        
    def setup_method(self):
        self.vars = {}
  
    def method_teardown(self):
        logger.info('{0}'.format("Teardown Chrome Webbrowser!"))        
        self.driver.quit()

    def method_close(self):
        logger.info('{0}'.format("Close Chrome Webbrowser!"))        
        self.driver.close()

    def method_get(self,what):
        logger.info('Open url:{0}'.format(what))        
        self.driver.get(what)
  
    def method_set_window_size(self,x_val, y_val):
        logger.info('Set Browser Size:{0}*{1}'.format(x_val, y_val))
        self.driver.set_window_size(x_val, y_val)

    def method_by_ID_click(self,obj_name,wait_time=5000):
        logger.info('Click by_ID:{0}'.format(obj_name))
        WebDriverWait(self.driver, wait_time).until(expected_conditions.visibility_of_element_located((By.ID, obj_name)))
        self.driver.find_element(By.ID, obj_name).click()    