# Generated by Selenium IDE
import os,sys

strabspath=os.path.abspath(__file__)
strdirname=os.path.dirname(strabspath)
str_split=os.path.split(strdirname)
prevdirname=str_split[0]
dirnamelib=os.path.join(prevdirname,"lib")
dirnamelog=os.path.join(prevdirname,"logs")
sys.path.append(dirnamelib)

from logger import logger
from readConfig import *
from api_selenium import *
from api_selenium_dir17x19x import *


if __name__ == '__main__':
  # Get present time
  local_time = time.localtime(time.time())
  start_time = local_time
  #print('Start Time is ', local_time.tm_year,'/',local_time.tm_mon,'/',local_time.tm_mday,' ',local_time.tm_hour,":",local_time.tm_min,":",local_time.tm_sec)
  #logging.error('Begin Time:')
  start_time=str(local_time.tm_year)+'/'+str(local_time.tm_mon)+'/'+str(local_time.tm_mday)+' '+\
              str(local_time.tm_hour)+":"+str(local_time.tm_min)+":"+str(local_time.tm_sec)
  logger.info('Start Time is: {0}'.format(start_time))
  
  # Read json file
  with open('config.json') as f:
    config_para = json.load(f)

  #local_dir1750_wanmode_setup=dir17x19x_internet_mode_setup()
  
  #go_url="http://220.18.1.1/"
  go_url="http://" + config_para["DUT_Config_WLAN"][0]["dut"]["lan_ip_address"]
  #go_url="http://192.168.0.1/"
  #go_url="http://dlinkrouter.local."
  #local_dir1750_wanmode_setup.dut_Login(go_url)
  #local_dir1750_wanmode_setup.dut_Sys_Reset()
  #local_dir1750_wanmode_setup.dut_Sys_Reboot()

  #local_dir1750_wanmode_setup.dut_internet_mode_pptp_manual()

  #local_dir1750_wanmode_setup.method_close()
  #local_dir1750_wanmode_setup.method_teardown()
  #Test_dir1750_internet_mode_setup.method_close()  

  local_dir1750_wifi2g5g_ch_setup=dir17x19x_wifi_2G5G_Setup()

  local_dir1750_wifi2g5g_ch_setup.dut_Login(go_url,**config_para["DUT_Config_WLAN"][0])
  #local_dir1750_wifi2g5g_ch_setup.wifi_SmartConnDisable();# "WPA/WPA2-Personal"
  
  # Converting Python dict to kwargs?
  # https://stackoverflow.com/questions/5710391/converting-python-dict-to-kwargs
  local_dir1750_wifi2g5g_ch_setup.wifi_2g_setup(**config_para["DUT_Config_WLAN"][0]) 
  #local_dir1750_wifi2g5g_ch_setup.wifi_5g_setup(**config_para["DUT_Config_WLAN"][0]) 

  local_dir1750_wifi2g5g_ch_setup.method_close()
  local_dir1750_wifi2g5g_ch_setup.method_teardown()
  
# Get the last time
local_time = time.localtime(time.time())
#print('Final Time is ', local_time.tm_year,'/',local_time.tm_mon,'/',local_time.tm_mday,' ',local_time.tm_hour,":",local_time.tm_min,":",local_time.tm_sec)
#logging.error('Finish Time:')
end_time=str(local_time.tm_year)+'/'+str(local_time.tm_mon)+'/'+str(local_time.tm_mday)+' '+\
          str(local_time.tm_hour)+":"+str(local_time.tm_min)+":"+str(local_time.tm_sec)
logger.info('End Time is: {0}'.format(end_time))
                