# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys

class Test_dir1750_wifi_2G5G_Setup():
  def __init__(self):
    self.driver = webdriver.Chrome()
    
  def setup_method(self):
    self.vars = {}
  
  def teardown_method(self):
    self.driver.quit()

  def close_method(self):
    self.driver.close()  
  
  def wifi_Login(self):
    self.driver.get("http://192.168.0.1/")
    self.driver.set_window_size(1080, 605)
    self.driver.find_element(By.ID, "logIn_btn").click()
  
  def wifi_SmartConnDisable(self):
    WebDriverWait(self.driver, 5000).until(expected_conditions.visibility_of_element_located((By.ID, "menu_Settings")))
    element = self.driver.find_element(By.ID, "menu_Settings")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.ID, "menuBtn_WiFi").click()
    WebDriverWait(self.driver, 5000).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "#RADIO_smart .chkbox_enabled")))
    self.driver.find_element(By.CSS_SELECTOR, "#RADIO_smart .chkbox_enabled").click()
    
    # Extend 2G option page
    self.driver.find_element(By.CSS_SELECTOR, ".radio24_advBtn > span").click()    
    WebDriverWait(self.driver, 5000).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "#coexistence_24_tr .chkbox_enabled")))
    self.driver.find_element(By.CSS_SELECTOR, "#coexistence_24_tr .chkbox_enabled").click()

    self.driver.find_element(By.ID, "Save_btn").click()
    WebDriverWait(self.driver, 50000).until(expected_conditions.visibility_of_element_located((By.ID, "popalert_ok")))
    self.driver.find_element(By.ID, "popalert_ok").click()
    
  def wifi_2g_ch_setup(self):
    WebDriverWait(self.driver, 5000).until(expected_conditions.visibility_of_element_located((By.ID, "menu_Settings")))   
    element = self.driver.find_element(By.ID, "menu_Settings")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.ID, "menuBtn_WiFi").click()
    
    WebDriverWait(self.driver, 5000).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, ".radio24_advBtn > span")))
    self.driver.find_element(By.CSS_SELECTOR, ".radio24_advBtn > span").click()
    
    self.driver.find_element(By.ID, "wifiName_24").clear()
    self.driver.find_element(By.ID, "password_24").clear()

    self.driver.find_element(By.ID, "wifiName_24").send_keys("testdlink-2G")
    self.driver.find_element(By.ID, "password_24").send_keys("00000000")
    self.driver.find_element(By.XPATH, "(//a[contains(@href, \'#\')])[8]").click()
    self.driver.find_element(By.LINK_TEXT, "1").click()
    self.driver.find_element(By.XPATH, "(//a[contains(@href, \'#\')])[12]").click()
    self.driver.find_element(By.LINK_TEXT, "Auto 20/40 MHz").click()
    self.driver.find_element(By.XPATH, "(//a[contains(@href, \'#\')])[14]").click()
    self.driver.find_element(By.LINK_TEXT, "Visible").click()

    WebDriverWait(self.driver, 5000).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, "#RADIO_5 > .advButton > span")))
    self.driver.find_element(By.CSS_SELECTOR, "#RADIO_5 > .advButton > span").click()
    self.driver.find_element(By.XPATH, "(//a[contains(@href, \'#\')])[30]").click()
    self.driver.find_element(By.LINK_TEXT, "Invisible").click()
    self.driver.find_element(By.ID, "Save_btn").click()
    WebDriverWait(self.driver, 50000).until(expected_conditions.visibility_of_element_located((By.ID, "popalert_ok")))
    self.driver.find_element(By.XPATH, "//button[@id=\'popalert_ok\']").click()
    
if __name__ == '__main__':
  local_dir1750_wifi_Setup=Test_dir1750_wifi_2G5G_Setup()

  local_dir1750_wifi_Setup.wifi_Login()
  #local_dir1750_wifi_Setup.wifi_SmartConnDisable()
  
  local_dir1750_wifi_Setup.wifi_2g_ch_setup()

  local_dir1750_wifi_Setup.close_method()
  local_dir1750_wifi_Setup.teardown_method()