# Generated by Selenium IDE
# 2019/10/11 Initial release 

import os,sys

strabspath=os.path.abspath(__file__)
strdirname=os.path.dirname(strabspath)
str_split=os.path.split(strdirname)
prevdirname=str_split[0]
dirnamelib=os.path.join(prevdirname,"lib")
dirnamelog=os.path.join(prevdirname,"logs")
sys.path.append(dirnamelib)

from logger import logger
from readConfig import *
from api_selenium import *
from api_selenium_dir17x19x import *


def dir17501950_wifi_2g_thtuput(*args, **kwargs):
  go_url="http://" + kwargs["dut"]["lan_ip_address"]
  
  logger.info('TestCase_ID:{0} TestCase_Desc:{1}'.format(kwargs["test_case"]["id"],kwargs["test_case"]["description"]))

  local_dir1750_wifi2g5g_ch_setup=dir17x19x_wifi_2G5G_Setup()

  local_dir1750_wifi2g5g_ch_setup.dut_Login(go_url,**kwargs)

  # Converting Python dict to kwargs?
  # https://stackoverflow.com/questions/5710391/converting-python-dict-to-kwargs
  local_dir1750_wifi2g5g_ch_setup.wifi_2g_setup(**kwargs) 

  local_dir1750_wifi2g5g_ch_setup.method_close()
  local_dir1750_wifi2g5g_ch_setup.method_teardown()

def dir17501950_wifi_5g_thtuput(*args, **kwargs):
  go_url="http://" + kwargs["dut"]["lan_ip_address"]
  
  logger.info('TestCase_ID:{0} TestCase_Desc:{1}'.format(kwargs["test_case"]["id"],kwargs["test_case"]["description"]))

  local_dir1750_wifi2g5g_ch_setup=dir17x19x_wifi_2G5G_Setup()

  local_dir1750_wifi2g5g_ch_setup.dut_Login(go_url,**kwargs)

  # Converting Python dict to kwargs?
  # https://stackoverflow.com/questions/5710391/converting-python-dict-to-kwargs
  local_dir1750_wifi2g5g_ch_setup.wifi_5g_setup(**kwargs) 

  local_dir1750_wifi2g5g_ch_setup.method_close()
  local_dir1750_wifi2g5g_ch_setup.method_teardown()

if __name__ == '__main__':
  # Get present time
  local_time = time.localtime(time.time())
  start_time = local_time
  #print('Start Time is ', local_time.tm_year,'/',local_time.tm_mon,'/',local_time.tm_mday,' ',local_time.tm_hour,":",local_time.tm_min,":",local_time.tm_sec)
  #logging.error('Begin Time:')
  start_time=str(local_time.tm_year)+'/'+str(local_time.tm_mon)+'/'+str(local_time.tm_mday)+' '+\
              str(local_time.tm_hour)+":"+str(local_time.tm_min)+":"+str(local_time.tm_sec)
  logger.info('Start Time is: {0}'.format(start_time))
  
  # Read json file
  with open('config.json') as f:
    config_para = json.load(f)
  
  #dir17501950_wifi_5g_thtuput(**config_para["DUT_Config_WLAN"][0])

  #dir17501950_wifi_2g_thtuput(**config_para["DUT_Config_WLAN"][0]);#testing purpose
  
  # WiFi 2G Thruput Test
  dir17501950_wifi_2g_thtuput(**config_para["DUT_Config_WLAN"][1]);pass
  dir17501950_wifi_2g_thtuput(**config_para["DUT_Config_WLAN"][2]);pass
  dir17501950_wifi_2g_thtuput(**config_para["DUT_Config_WLAN"][3]);pass

  # WiFi 5G Thruput Test  
  dir17501950_wifi_5g_thtuput(**config_para["DUT_Config_WLAN"][4]);pass
  dir17501950_wifi_5g_thtuput(**config_para["DUT_Config_WLAN"][5]);pass

# Get the last time
local_time = time.localtime(time.time())
#print('Final Time is ', local_time.tm_year,'/',local_time.tm_mon,'/',local_time.tm_mday,' ',local_time.tm_hour,":",local_time.tm_min,":",local_time.tm_sec)
#logging.error('Finish Time:')
end_time=str(local_time.tm_year)+'/'+str(local_time.tm_mon)+'/'+str(local_time.tm_mday)+' '+\
          str(local_time.tm_hour)+":"+str(local_time.tm_min)+":"+str(local_time.tm_sec)
logger.info('End Time is: {0}'.format(end_time))
                